# Generated by Django 6.0.6 on 2026-06-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('module_type', models.CharField(choices=[('core', 'Core'), ('addon', 'Add-on')], default='addon', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='unique_module_per_company')],
            },
        ),
    ]
