# Generated by Django 6.0.6 on 2026-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('post', 'Post'), ('reverse', 'Reverse'), ('close_period', 'Close period'), ('activate_module', 'Activate module'), ('deactivate_module', 'Deactivate module')], max_length=40),
        ),
    ]
