# Generated by Django 6.0.6 on 2026-06-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')], default=1),
        ),
    ]
