# Generated by Django 6.0.6 on 2026-06-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashbankaccount',
            name='unique_cashbank_account_mapping_per_company',
        ),
    ]
