# Generated by Django 6.0.6 on 2026-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_account_is_postable_fiscalyearclosing'),
        ('cashbank', '0002_remove_cashbankaccount_unique_cashbank_account_mapping_per_company'),
        ('companies', '0003_company_fiscal_year_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbankaccount',
            name='account_holder',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='cashbankaccount',
            name='account_kind',
            field=models.CharField(choices=[('cash', 'Kas'), ('bank', 'Bank'), ('ewallet', 'E-Wallet')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='cashbankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='cashbankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cashbankaccount',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashbankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='cashbankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_number', ''), _negated=True), fields=('company', 'account_number'), name='unique_cashbank_account_number_per_company'),
        ),
    ]
