# Generated by Django 6.0.6 on 2026-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0003_cashbankaccount_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbanktransaction',
            name='admin_fee_borne_by',
            field=models.CharField(choices=[('source', 'Rekening sumber'), ('destination', 'Rekening tujuan')], default='destination', max_length=20),
        ),
    ]
