# Generated by Django 6.0.6 on 2026-06-17 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_uuid_fields'),
        ('companies', '0002_company_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(choices=[('income_statement', 'Laba Rugi'), ('balance_sheet', 'Neraca')], max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_report_templates', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=180)),
                ('line_type', models.CharField(choices=[('heading', 'Heading'), ('account_group', 'Account group'), ('formula', 'Formula'), ('blank', 'Blank')], max_length=30)),
                ('indent_level', models.PositiveSmallIntegerField(default=0)),
                ('is_bold', models.BooleanField(default=False)),
                ('show_when_zero', models.BooleanField(default=True)),
                ('formula', models.CharField(blank=True, max_length=255)),
                ('accounts', models.ManyToManyField(blank=True, related_name='report_lines', to='accounting.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.financialreportline')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.financialreporttemplate')),
            ],
            options={
                'ordering': ['template', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialreporttemplate',
            constraint=models.UniqueConstraint(fields=('company', 'report_type', 'name'), name='unique_report_template_name_per_company_type'),
        ),
        migrations.AddConstraint(
            model_name='financialreportline',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_report_line_code_per_template'),
        ),
    ]
