# Generated by Django 6.0.6 on 2026-06-17 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_financialreporttemplate_financialreportline_and_more'),
        ('companies', '0002_company_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('activity_type', models.CharField(choices=[('operating', 'Operasi'), ('investing', 'Investasi'), ('financing', 'Pendanaan')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_categories', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'activity_type', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountCashFlowMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_mappings', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_cash_flow_mappings', to='companies.company')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_mappings', to='accounting.cashflowcategory')),
            ],
            options={
                'ordering': ['company__name', 'account__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashflowcategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_cash_flow_category_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='accountcashflowmapping',
            constraint=models.UniqueConstraint(fields=('company', 'account'), name='unique_cash_flow_mapping_per_account'),
        ),
    ]
