# Generated by Django 6.0.6 on 2026-06-17 07:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_cashflowcategory_accountcashflowmapping_and_more'),
        ('companies', '0002_company_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPeriodBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('opening_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('opening_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('movement_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('movement_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('closing_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('closing_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_balances', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_period_balances', to='companies.company')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balances', to='accounting.accountingperiod')),
            ],
            options={
                'ordering': ['period__year', 'period__month', 'account__code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'account', 'period'), name='unique_account_period_balance')],
            },
        ),
    ]
